// frontend/src/components/symptomChecker.vue
<template>
    <div class="container">
      <h2>Symptom Checker</h2>
  
      <form @submit.prevent="submitForm" class="form">
        <div class="form-group">
          <label for="uuid">Patient UUID:</label>
          <input v-model="uuid" id="uuid" type="text" required />
        </div>
  
        <div class="form-group">
          <label for="symptom">Symptom Description:</label>
          <textarea v-model="symptom" id="symptom" rows="4" required></textarea>
        </div>
  
        <button type="submit">Check Symptoms</button>
      </form>
  
      <div v-if="response" class="response">
        <h3>Patient Info</h3>
        <pre>{{ response.patient_info }}</pre>
  
        <h3>Consultation History</h3>
        <pre>{{ response.consultation_history }}</pre>
  
        <h3>AI Response</h3>
        <p>{{ response.ai_response }}</p>
      </div>
    </div>
  </template>
  
  <script>
  export default {
    name: "SymptomChecker",
    data() {
      return {
        uuid: "",
        symptom: "",
        response: null,
      };
    },
    methods: {
      async submitForm() {
        try {
          const res = await fetch("http://localhost:8000/check-symptoms", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              uuid: this.uuid,
              symptom_description: this.symptom,
            }),
          });
  
          if (!res.ok) {
            throw new Error("Failed to fetch response");
          }
  
          const data = await res.json();
          this.response = data;
        } catch (error) {
          console.error(error);
          alert("Something went wrong. Please try again.");
        }
      },
    },
  };
  </script>
  
  <style scoped>
  .container {
    max-width: 600px;
    margin: 40px auto;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px #ccc;
    background-color: #f9f9f9;
  }
  
  h2 {
    text-align: center;
  }
  
  .form-group {
    margin-bottom: 15px;
  }
  
  label {
    font-weight: bold;
  }
  
  input,
  textarea {
    width: 100%;
    padding: 8px;
    margin-top: 5px;
    box-sizing: border-box;
  }
  
  button {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 16px;
    background-color: #007acc;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }
  
  .response {
    margin-top: 30px;
    background: #fff;
    padding: 20px;
    border-radius: 5px;
  }
  </style>

// vite-project/src/pages/SymptomChecker.tsx
import { useState } from 'react';
import axios from 'axios';

const SymptomChecker = () => {
    const [uuid, setUuid] = useState('');
    const [symptom, setSymptom] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [result, setResult] = useState<any>(null);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!uuid.trim() || !symptom.trim()) {
            setError('Please enter both UUID and symptom.');
            return;
        }

        setError('');
        setLoading(true);
        setResult(null);

        try {
            const response = await axios.post('http://localhost:4000/check-symptoms', {
                uuid,
                symptom_description: symptom,
            });
            setResult(response.data);
        } catch (err: any) {
            setError('Something went wrong. Please try again.');
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div style={{ padding: '40px', maxWidth: '700px', margin: '0 auto', fontFamily: 'Arial, sans-serif' }}>
            <h1 style={{ marginBottom: '30px', textAlign: 'center' }}>Symptom Checker</h1>

            <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                <input
                    type="text"
                    placeholder="Enter patient UUID..."
                    value={uuid}
                    onChange={(e) => setUuid(e.target.value)}
                    style={{
                        padding: '12px',
                        fontSize: '16px',
                        borderRadius: '5px',
                        border: '1px solid #ccc',
                    }}
                />
                <input
                    type="text"
                    placeholder="Describe your symptoms..."
                    value={symptom}
                    onChange={(e) => setSymptom(e.target.value)}
                    style={{
                        padding: '12px',
                        fontSize: '16px',
                        borderRadius: '5px',
                        border: '1px solid #ccc',
                    }}
                />
                <button
                    type="submit"
                    disabled={loading}
                    style={{
                        padding: '12px',
                        fontSize: '16px',
                        borderRadius: '5px',
                        backgroundColor: '#007bff',
                        color: '#fff',
                        border: 'none',
                        cursor: 'pointer',
                    }}
                >
                    {loading ? 'Checking...' : 'Submit'}
                </button>
            </form>

            {error && (
                <p style={{ color: 'red', marginTop: '20px', textAlign: 'center' }}>{error}</p>
            )}

            {result && (
                <div style={{ marginTop: '30px' }}>
                    <div style={{ background: '#f9f9f9', padding: '20px', borderRadius: '8px', marginBottom: '20px' }}>
                        <h3>AI Response:</h3>
                        <p>{result.ai_response}</p>
                    </div>

                    <div style={{ background: '#f1f1f1', padding: '20px', borderRadius: '8px', marginBottom: '20px' }}>
                        <h4>Patient Info:</h4>
                        <pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(result.patient_info, null, 2)}</pre>
                    </div>

                    <div style={{ background: '#f1f1f1', padding: '20px', borderRadius: '8px' }}>
                        <h4>Consultation History:</h4>
                        <pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(result.consultation_history, null, 2)}</pre>
                    </div>
                </div>
            )}
        </div>
    );
};

export default SymptomChecker;
